include:
  - board: nice_nano_v2
    shield: settings_reset
  - board: nice_nano_v2
    shield: klor_dongle #dongle_display
    # snippet: studio-rpc-usb-uart
    # cmake-args: -DCONFIG_ZMK_STUDIO=y -DCONFIG_ZMK_USB=y
  - board: nice_nano_v2
    shield: klor_left
    snippet: studio-rpc-usb-uart
  - board: nice_nano_v2
    shield: klor_right