include:
  - board: nice_nano_v2
    shield: settings_reset

  - board: nice_nano_v2
    shield: klor_dongle dongle_display
    snippet: studio-rpc-usb-uart zmk-usb-logging
    cmake-args: -DCONFIG_ZMK_STUDIO=y
  
  - board: nice_nano_v2
    shield: klor_left
    snippet: zmk-usb-logging
  
  - board: nice_nano_v2
    shield: klor_right
    snippet: zmk-usb-logging